bindPort = 17000

# If you want to support virtual host, you must set the http port for listening (optional)
# Note: http port and https port can be same with bindPort
vhostHTTPPort = 1180
#vhostHTTPSPort = 443